name: Build R Markdown (please)

on:
  push:
    paths:
      - 'lectures/setup_1.Rmd'  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set CRAN Mirror
        run: echo "options(repos = c(CRAN = 'https://cran.rstudio.com'))" >> $GITHUB_WORKSPACE/.Rprofile
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
          Rscript -e 'install.packages("tinytex", repos="http://cran.rstudio.com/"); tinytex::install_tinytex()'
          Rscript -e 'tinytex:::install_prebuilt("tinytex")'
          Rscript -e 'install.packages(c("knitr", "BiocManager"), repos="http://cran.rstudio.com/")' 
          Rscript -e 'BiocManager::install("BiocStyle")'
      
      - name: Install bookdown package
        run: Rscript -e 'install.packages("bookdown", repos="http://cran.rstudio.com/")'

      - name: Set Git identity
        run: |
          git config --global user.email "pedstunite@gmail.com"
          git config --global user.name "Pedro Miura"

          
      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("lectures/setup_1.Rmd")'

#      - name: Convert to PDF
#        run: Rscript -e 'rmarkdown::render("lectures/setup_1.Rmd", output_format = "pdf_document")'

      - name: Commit and push changes
        run: |
          git add lectures/setup_1.html
          #git add lectures/setup_1.pdf
          git commit -m "Render Lecture_2.Rmd to HTML and PDF"
          git push origin HEAD:main
