name: Build R Markdown (please)

on:
  push:
    paths:
      - 'lectures/lecture_2.Rmd'  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set CRAN Mirror
        run: echo "options(repos = c(CRAN = 'https://cran.rstudio.com'))" >> $GITHUB_WORKSPACE/.Rprofile
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
          Rscript -e 'install.packages("tinytex", repos="http://cran.rstudio.com/"); tinytex::install_tinytex()'
          Rscript -e 'tinytex:::install_prebuilt("tinytex")'
      
      - name: Install bookdown package
        run: Rscript -e 'install.packages("bookdown", repos="http://cran.rstudio.com/")'
        
      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("lectures/lecture_2.Rmd")'

      - name: Convert to PDF
        run: Rscript -e 'rmarkdown::render("lectures/lecture_2.Rmd", output_format = "pdf_document")'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rmarkdown-output
          path: lectures/lecture_2.html, lectures/lecture_2.pdf
